/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface LoadingSpinner {
    }
    interface SearchInput {
    }
    interface SearchPage {
    }
    interface SearchResult {
        "userInfo": any;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {
    }
    var HTMLLoadingSpinnerElement: {
        prototype: HTMLLoadingSpinnerElement;
        new (): HTMLLoadingSpinnerElement;
    };
    interface HTMLSearchInputElement extends Components.SearchInput, HTMLStencilElement {
    }
    var HTMLSearchInputElement: {
        prototype: HTMLSearchInputElement;
        new (): HTMLSearchInputElement;
    };
    interface HTMLSearchPageElement extends Components.SearchPage, HTMLStencilElement {
    }
    var HTMLSearchPageElement: {
        prototype: HTMLSearchPageElement;
        new (): HTMLSearchPageElement;
    };
    interface HTMLSearchResultElement extends Components.SearchResult, HTMLStencilElement {
    }
    var HTMLSearchResultElement: {
        prototype: HTMLSearchResultElement;
        new (): HTMLSearchResultElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "loading-spinner": HTMLLoadingSpinnerElement;
        "search-input": HTMLSearchInputElement;
        "search-page": HTMLSearchPageElement;
        "search-result": HTMLSearchResultElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface LoadingSpinner {
    }
    interface SearchInput {
        "onSearchClicked"?: (event: CustomEvent<string>) => void;
        "onSearchInputChanged"?: (event: CustomEvent<string>) => void;
    }
    interface SearchPage {
    }
    interface SearchResult {
        "userInfo"?: any;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "loading-spinner": LoadingSpinner;
        "search-input": SearchInput;
        "search-page": SearchPage;
        "search-result": SearchResult;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "loading-spinner": LocalJSX.LoadingSpinner & JSXBase.HTMLAttributes<HTMLLoadingSpinnerElement>;
            "search-input": LocalJSX.SearchInput & JSXBase.HTMLAttributes<HTMLSearchInputElement>;
            "search-page": LocalJSX.SearchPage & JSXBase.HTMLAttributes<HTMLSearchPageElement>;
            "search-result": LocalJSX.SearchResult & JSXBase.HTMLAttributes<HTMLSearchResultElement>;
        }
    }
}
